/* The following code was generated by JFlex 1.4.3 on 30.11.15 23:52 */

package org.pcsoft.plugins.intellij.inno_setup.script.parser.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.pcsoft.plugins.intellij.inno_setup.script.parser.lexer.IssTokenFactory;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30.11.15 23:52 from the specification file
 * <tt>G:/Workspace/IntelliJ/intellij-plugin.inno-setup/src/org/pcsoft/plugins/intellij/inno_setup/script/parser/lexer/iss.flex</tt>
 */
class _IssLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int CODE = 4;
  public static final int YYINITIAL = 0;
  public static final int ALLOW_ALL = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  3,  2, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\3\1\0\1\15"+
    "\1\12\4\0\2\11\1\0\1\17\1\0\1\17\1\7\1\0\12\16"+
    "\1\5\1\4\1\0\1\6\3\0\2\10\1\20\27\10\1\13\1\0"+
    "\1\14\1\0\1\10\1\0\3\10\1\22\1\23\11\10\1\21\13\10"+
    "\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\1\1\11\1\10\1\1\1\4\2\1"+
    "\1\4\1\5\1\6\1\7\1\10\1\1\1\10\1\1"+
    "\1\4\1\1\1\12\1\0\1\13\1\0\1\1\1\0"+
    "\2\14\2\1\1\12\5\1\1\15\1\16\1\1\1\15"+
    "\1\16\5\1\2\17";

  private static int [] zzUnpackAction() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\24\0\50\0\74\0\120\0\144\0\170\0\214"+
    "\0\144\0\144\0\144\0\144\0\240\0\144\0\264\0\310"+
    "\0\334\0\360\0\u0104\0\u0118\0\u012c\0\u012c\0\u012c\0\u012c"+
    "\0\u012c\0\u0140\0\u0154\0\u0168\0\u017c\0\u0190\0\u01a4\0\264"+
    "\0\310\0\144\0\u01b8\0\u01cc\0\u0104\0\144\0\u0104\0\u01e0"+
    "\0\u01f4\0\u0154\0\u0208\0\u021c\0\u0190\0\u0230\0\u0244\0\u01b8"+
    "\0\120\0\u0258\0\u0208\0\u012c\0\u026c\0\u0280\0\u0294\0\u02a8"+
    "\0\u02bc\0\120\0\u012c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\2\5\1\20\1\21\1\22\4\15"+
    "\1\5\1\6\1\7\1\10\1\23\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\24\1\5\1\20\1\21\1\22"+
    "\4\15\1\25\1\6\1\7\1\10\1\26\1\27\1\30"+
    "\1\31\1\32\1\16\1\33\2\25\1\20\1\34\1\35"+
    "\4\32\1\25\1\6\1\7\1\10\1\36\1\27\1\30"+
    "\1\31\1\32\1\16\1\33\1\37\1\25\1\20\1\34"+
    "\1\35\4\32\1\5\7\0\1\5\1\0\3\5\1\0"+
    "\6\5\25\0\1\6\25\0\1\10\20\0\1\5\7\0"+
    "\1\15\1\0\3\5\1\0\1\15\1\5\4\15\1\5"+
    "\7\0\1\40\1\0\3\5\1\0\1\40\1\5\4\40"+
    "\1\41\2\0\6\41\1\0\3\41\1\42\6\41\1\5"+
    "\6\0\1\43\1\15\1\0\3\5\1\0\1\21\1\5"+
    "\4\15\1\5\7\0\1\5\1\0\3\5\1\0\1\44"+
    "\5\5\1\45\1\46\1\47\21\45\1\5\7\0\1\50"+
    "\1\0\3\5\1\0\1\50\1\5\1\51\3\50\1\25"+
    "\3\0\5\25\1\0\3\25\1\0\7\25\3\0\4\25"+
    "\1\32\1\0\3\25\1\0\1\32\1\25\4\32\1\25"+
    "\3\0\4\25\1\52\1\0\3\25\1\0\1\52\1\25"+
    "\4\52\1\25\3\0\3\25\1\53\1\32\1\0\3\25"+
    "\1\0\1\34\1\25\4\32\1\25\3\0\5\25\1\0"+
    "\3\25\1\0\1\54\5\25\1\55\1\46\1\47\1\45"+
    "\5\55\1\45\3\55\1\45\6\55\1\25\3\0\4\25"+
    "\1\56\1\0\3\25\1\0\1\56\1\25\1\57\3\56"+
    "\16\0\1\60\5\0\1\5\6\0\1\43\1\5\1\0"+
    "\3\5\1\0\1\44\6\5\7\0\1\50\1\0\2\5"+
    "\1\61\1\0\1\50\1\5\4\50\1\5\7\0\1\50"+
    "\1\0\2\5\1\61\1\0\1\50\1\5\1\50\1\62"+
    "\2\50\1\25\3\0\5\25\1\0\3\25\1\0\1\63"+
    "\6\25\3\0\3\25\1\53\1\25\1\0\3\25\1\0"+
    "\1\54\6\25\3\0\4\25\1\56\1\0\2\25\1\64"+
    "\1\0\1\56\1\25\4\56\1\25\3\0\4\25\1\56"+
    "\1\0\2\25\1\64\1\0\1\56\1\25\1\56\1\65"+
    "\2\56\1\5\7\0\1\50\1\0\2\5\1\61\1\0"+
    "\1\50\1\5\2\50\1\66\1\50\1\25\3\0\4\25"+
    "\1\56\1\0\2\25\1\64\1\0\1\56\1\25\2\56"+
    "\1\67\1\56\1\5\7\0\1\50\1\0\2\5\1\61"+
    "\1\0\1\50\1\5\3\50\1\70\1\25\3\0\4\25"+
    "\1\56\1\0\2\25\1\64\1\0\1\56\1\25\3\56"+
    "\1\71\1\5\7\0\1\50\1\0\2\5\1\72\1\0"+
    "\1\50\1\5\4\50\1\25\3\0\4\25\1\56\1\0"+
    "\2\25\1\73\1\0\1\56\1\25\4\56";

  private static int [] zzUnpackTrans() {
    int [] result = new int[720];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\1\1\11\2\1\4\11\1\1\1\11\22\1"+
    "\1\0\1\11\1\0\1\1\1\0\1\11\25\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;


  _IssLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _IssLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 82) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL.charAt(zzMarkedPosL-1)) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL.charAt(zzMarkedPosL) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL.charAt(zzMarkedPosL) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { return IssTokenFactory.COMMENT;
          }
        case 16: break;
        case 11: 
          { return IssTokenFactory.STRING;
          }
        case 17: break;
        case 15: 
          { yybegin(CODE); return IssTokenFactory.SECTION_TITLE;
          }
        case 18: break;
        case 6: 
          { yybegin(ALLOW_ALL); return IssTokenFactory.OPERATOR_EQUAL;
          }
        case 19: break;
        case 13: 
          { return IssTokenFactory.NUMBER;
          }
        case 20: break;
        case 10: 
          { return IssTokenFactory.COMPILER_DIRECTIVE;
          }
        case 21: break;
        case 4: 
          { return IssTokenFactory.OPERATOR_SEMICOLON;
          }
        case 22: break;
        case 7: 
          { return IssTokenFactory.OPERATOR_POINT;
          }
        case 23: break;
        case 14: 
          { yybegin(YYINITIAL); return IssTokenFactory.SECTION_TITLE;
          }
        case 24: break;
        case 2: 
          { yybegin(YYINITIAL); return IssTokenFactory.CRLF;
          }
        case 25: break;
        case 3: 
          { return IssTokenFactory.WHITE_SPACE;
          }
        case 26: break;
        case 1: 
          { return IssTokenFactory.WORD;
          }
        case 27: break;
        case 8: 
          { return IssTokenFactory.NAME;
          }
        case 28: break;
        case 9: 
          { return IssTokenFactory.BAD_CHARACTER;
          }
        case 29: break;
        case 5: 
          { return IssTokenFactory.OPERATOR_COLON;
          }
        case 30: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
